### ISSUE TITLE
[BUG] Pinned tabs disappear with too many tabs open

### ISSUE THREAD

**Issue by AdamXweb** [AdamXweb/WhiteSurFirefoxThemeMacOS#104]
### Describe the problem

Tab scroll navigation overlaps the pinned tabs.

Need to confirm if is theme behaviour or Firefox behaviour

### Version

1.5.3

### OS

MacOS

### Firefox Version

118.0.1

### Install Options

n/a

### Colour Theme

n/a

### Additional info

<img width="119" alt="Screenshot 2023-10-04 at 10 49 07 am" src="https://github.com/AdamXweb/WhiteSurFirefoxThemeMacOS/assets/6800453/0bb7d0dd-44d6-495c-88d5-df4c439433ca">
<img width="113" alt="Screenshot 2023-10-04 at 10 47 45 am" src="https://github.com/AdamXweb/WhiteSurFirefoxThemeMacOS/assets/6800453/d560c019-a496-4f2e-9b46-33adb73a207d">

### Please tick the boxes

- [X] You are using a [current](https://github.com/AdamXweb/WhiteSurFirefoxThemeMacOS/releases/) version of the theme. (check the date associated with the version)
- [X] You've checked that this [issue hasn't already been raised](https://github.com/adamxweb/WhiteSurFirefoxThemeMacOS/issues?q=is%3Aissue)

**Comment by vcoss-adam** [comment]
![image](https://github.com/AdamXweb/WhiteSurFirefoxThemeMacOS/assets/132973209/96111ca0-f514-4e90-9df3-fb4c9aedc503)
On Windows, multiple pinned tabs adds space for tabs but aren't visible or clickable
