### ISSUE TITLE
[BUG] Selected tab background colour changed

### ISSUE THREAD

**Issue by AdamXweb** [AdamXweb/WhiteSurFirefoxThemeMacOS#108]
### Describe the problem

See info of some changes to the selected queries including [selected] changing from [selected="true"].
https://www.reddit.com/r/FirefoxCSS/comments/17eoyyo/the_custom_tab_background_colour_is_no_longer_set/

"[also [visuallyselected="true"] will become obsolete..](https://www.reddit.com/r/FirefoxCSS/comments/17eoyyo/comment/k6535xb/?utm_source=reddit&utm_medium=web2x&context=3)" 

https://github.com/AdamXweb/WhiteSurFirefoxThemeMacOS/blob/a9324042745302be37e18a3807091ff9599ae6be/chrome/WhiteSur/parts/tabsbar.css#L271

### Version

1.5.3

### OS

MacOS 14

### Firefox Version

119

### Install Options

n/a

### Colour Theme

n/a

### Additional info

<img width="804" alt="Screenshot 2023-10-26 at 7 07 48 pm" src="https://github.com/AdamXweb/WhiteSurFirefoxThemeMacOS/assets/6800453/9eacbf7a-ff7c-4327-a2f6-99d2a5b683b9">

### Please tick the boxes

- [X] You are using a [current](https://github.com/AdamXweb/WhiteSurFirefoxThemeMacOS/releases/) version of the theme. (check the date associated with the version)
- [X] You've checked that this [issue hasn't already been raised](https://github.com/adamxweb/WhiteSurFirefoxThemeMacOS/issues?q=is%3Aissue)

**Comment by donkee** [comment]
Can confirm that changing all `selected=true` and `selected="true"` in `WhiteSur/parts/tabsbar.css` fixes this issue on Firefox 119
