### ISSUE TITLE
 [BUG] Search bar's dropdown background became transparent

### ISSUE THREAD

**Issue by zhen737** [AdamXweb/WhiteSurFirefoxThemeMacOS#112]
### Describe the problem

Kind of another bug from fixed of last issue #109 :  After updating to 1.5.4, the background of the search bar dropdown became transparent.

### Version

1.5.4

### OS

Windows 11

### Firefox Version

121.0

### Install Options

none

### Colour Theme

Default Dark, Default Light

### Additional info

![Screenshot 2024-01-06 181505](https://github.com/AdamXweb/WhiteSurFirefoxThemeMacOS/assets/29022772/f63be1c8-7d8b-46da-b74d-906e4b3a9b3a)

![Screenshot 2024-01-06 182033](https://github.com/AdamXweb/WhiteSurFirefoxThemeMacOS/assets/29022772/9b3cebd4-89cf-4826-9bf5-9c2cfec90996)

### Please tick the boxes

- [X] You are using a [current](https://github.com/AdamXweb/WhiteSurFirefoxThemeMacOS/releases/) version of the theme. (check the date associated with the version)
- [X] You've checked that this [issue hasn't already been raised](https://github.com/adamxweb/WhiteSurFirefoxThemeMacOS/issues?q=is%3Aissue)

**Comment by AdamXweb** [comment]
Hi @zhen737 thanks for submitting the ticket. Can you confirm if the issue is present just in the search bar or the address bar too?
Looks like this is a windows only bug

**Comment by zhen737** [comment]
It only present in the search bar, address bar is fine.

![Screenshot 2024-01-06 235722](https://github.com/AdamXweb/WhiteSurFirefoxThemeMacOS/assets/29022772/b60e150e-afeb-4dab-88df-d09055f1c764)

![Screenshot 2024-01-06 235843](https://github.com/AdamXweb/WhiteSurFirefoxThemeMacOS/assets/29022772/9237519e-e182-4b2f-b55a-9881e80719fb)

**Comment by Ramen-LadyHKG** [comment]
Confirm this issue exist in Linux's Firefox, Floorp as well.

**Comment by AdamXweb** [comment]
Can confirm issue is also in Macos version - looking into it
![54468](https://github.com/user-attachments/assets/9c7dded1-fa6a-4a2e-b99c-93134cbb3e7b)

**Comment by AdamXweb** [comment]
![36762](https://github.com/user-attachments/assets/79647de0-e25a-48fa-b929-ba11964b5759)
Fixed styling for separate search
