### ISSUE TITLE
[FEAT] MacOS title bar

### ISSUE THREAD

**Issue by ruslya7** [AdamXweb/WhiteSurFirefoxThemeMacOS#115]
### Describe the solution you'd like

Hello, @AdamXweb I'm sorry if i wrongly created this topic,but i want to ask you if it's possitble to recreate macOS title bar in Chrome or Chromium . I mean, i want to use a default Chrome UI but to move close buttons from right to left side and make them rounded and colorful like in macOS. Please answer me if it's possible somehow. I'm on Windows 10 if it's matters 🙏 

### Priority

Medium (Would be very useful)

### Is this something you would be keen to implement

None

**Comment by AdamXweb** [comment]
Hi @ruslya7,
Thanks for opening the feature request.
This would be cool, however is outside the scope of this theme and I won't be able to work on it. 
There may be a similar css community for chrome where some people are able to help
