### ISSUE TITLE
[BUG] Tab labels too short

### ISSUE THREAD

**Issue by hungry-scientist** [AdamXweb/WhiteSurFirefoxThemeMacOS#116]
### Describe the problem

How can I extend the tab label text width so that I can see more clearly what websites I've opened? I can't seem to figure it out just by poking with the browser toolbox. Could someone please help? 

<img width="1019" alt="Screenshot 2024-04-14 at 08 37 00" src="https://github.com/AdamXweb/WhiteSurFirefoxThemeMacOS/assets/166983142/e5bb577e-6106-4a7b-81e9-28eba36c6c76">

### Version

1.4.4

### OS

MacOS 14.1

### Firefox Version

124.0.0.2

### Install Options

-s

### Colour Theme

No

### Please tick the boxes

- [X] You are using a [current](https://github.com/AdamXweb/WhiteSurFirefoxThemeMacOS/releases/) version of the theme. (check the date associated with the version)
- [X] You've checked that this [issue hasn't already been raised](https://github.com/adamxweb/WhiteSurFirefoxThemeMacOS/issues?q=is%3Aissue)

**Comment by AdamXweb** [comment]
Hi hungry-scientist,
thanks for submitting the bug.
I'll look into this, as i believe it may be related to the -s install option.
Could you try installing without it to test?
This is what I get:
<img width="897" alt="Screenshot 2024-04-14 at 6 53 10 PM" src="https://github.com/AdamXweb/WhiteSurFirefoxThemeMacOS/assets/6800453/45f9edd8-7c06-41e3-9cc4-2a56d223ffe3">

Then again, it does raise an issue where there is too much padding in the URL bar also:
<img width="376" alt="Screenshot 2024-04-14 at 6 54 19 PM" src="https://github.com/AdamXweb/WhiteSurFirefoxThemeMacOS/assets/6800453/9898c3e4-2ad3-467d-8570-1f39ebb3c256">

**Comment by AdamXweb** [comment]
@hungry-scientist Also, can you please check the version of the theme you're using?

**Comment by hungry-scientist** [comment]
Hey, thanks for the prompt response! Re-installing definitely helped, but I think it's the swapping of the close button that causes the issue. I remember I had to adapt your code to actually swap the button to the left (by default the close button just pushes in the tab labels and shrinks them, but I found that it would only move to the left if I changed the order value from 0 to -1 – but then the tab labels stay short). I dodn't mention installing the theme with this since I just added the code to my userchrome.css. Could you test the theme with the code below and see if anything else needs adjusting? 

Thanks so much, really appreciate the support!

```

/* Left hand side tab close */

@namespace url(http://www.mozilla.org/keymaster/gatekeeper/there.is.only.xul);

.tab-content:not([pinned])::before,
.tab-content:not([pinned])::after {
    display: flex;
    content: "";
    flex-grow: 2
}

.tab-content:not([pinned])::after {
    flex-grow: 1;
}
/* Place close button on left side */
.tab-content {
    display: flex !important;
}

.tab-close-button {
    order: -1
}

.tab-icon-stack{
    padding-left: 1px !important;
}
.tabbrowser-tab[class*="identity-color-"][pinned] .tab-content{
    display:flex !important;
}
.tab-content:not([pinned])::before, .tab-content:not([pinned])::after {
  flex-grow: 1;
```

**Comment by pauldunahoo** [comment]
I am experiencing the same issue. Removing the theme and then re-installing without -s did not resolve the issue.

**Comment by AdamXweb** [comment]
This is fixed from https://github.com/AdamXweb/WhiteSurFirefoxThemeMacOS/commit/1932941731b0fd75980f0343affdb95144546ecd
