### ISSUE TITLE
Tab Close Button on Left

### ISSUE THREAD

**Issue by samwainwright** [AdamXweb/WhiteSurFirefoxThemeMacOS#13]
**Describe the solution you'd like**
To match Safari's positioning of the close tab button, it would be great to move this to the left of the tab, especially MacOS where everything window/tab related is on the left.

**Additional context**
Safari:
<img width="499" alt="image" src="https://user-images.githubusercontent.com/41054489/117330095-3f446200-ae8d-11eb-9dfc-87a88d6e3446.png">
Firefox:
<img width="266" alt="image" src="https://user-images.githubusercontent.com/41054489/117330157-4e2b1480-ae8d-11eb-9a09-f6a605b02936.png">

**Comment by AdamXweb** [comment]
Would be interesting!
I'd like to implement it as an option during the install phase, as I feel locations of buttons can come down to user preference, even though the theme is mostly based on safari.

**Comment by FraserEmbrey** [comment]
I'd like to add +1 to requests for this issue, or at least put how to swap it into the readme.
Trying the typical ways to do this doesn't seem to work with this theme.

**Comment by Parthvsquare** [comment]
i too would like this feature to see the daylight. count me in

**Comment by AdamXweb** [comment]
So this is a work in progress, but if you want to try it out without the styling changes, you can test the following:
```
/* Place close button on left side */
.tab-content {
	display: -moz-box !important;
}
.tab-close-button {
	-moz-box-ordinal-group: 0
}
```
I'll be releasing within the week with better styling and guides to implement it

**Comment by samwainwright** [comment]
@AdamXweb that works! Looking forward to seeing the new release and the full style guide. For now I'm happy to have the wonky tab title:
![image](https://user-images.githubusercontent.com/41054489/117854246-37b3fd00-b281-11eb-9b65-6717d760346e.png)

**Comment by Parthvsquare** [comment]
I foolishly tried adding `padding-right: 2px;` It didn't work. But i am happy with the result. Thanks man

**Comment by samwainwright** [comment]
Thanks to everyone who's contributed on this! I need to be careful what I wish for as I'm now struggling to tell Firefox and Safari apart! 😂

**Comment by AdamXweb** [comment]
An install option is now available with the flag `-c` to add the close button on the left hand side.

**Comment by AdamXweb** [comment]
![Uploading Screen Shot 2021-05-17 at 8.28.03 pm.png…]()

**Comment by FraserEmbrey** [comment]
Having an issue:
Says `option requires an argument -- c`

<img width="635" alt="Screenshot 2021-05-17 at 11 38 17" src="https://user-images.githubusercontent.com/7635426/118475614-60fede00-b704-11eb-97b4-1f01445981a4.png">

**Comment by AdamXweb** [comment]
> Having an issue:
> 
> Says `option requires an argument -- c`
> 
> 
> 
> <img width="635" alt="Screenshot 2021-05-17 at 11 38 17" src="https://user-images.githubusercontent.com/7635426/118475614-60fede00-b704-11eb-97b4-1f01445981a4.png">
> 
> 
> 
> This was on master branch as in the above screenshot
> 
> 

What OS are you using?

**Comment by FraserEmbrey** [comment]
11.3.1

**Comment by AdamXweb** [comment]
Give it another go, should be fixed now!

**Comment by FraserEmbrey** [comment]
It does work now, thanks so much!

Sorry I wasn't any help, I don't really use getopts (sometimes use args in fish but that's about it).

**Comment by AdamXweb** [comment]
> It does work now, thanks so much!
> 
> Sorry I wasn't any help, I don't really use getopts (sometimes use args in fish but that's about it).

Not a problem!
I'd appreciate a star if you found the theme useful :)
