### ISSUE TITLE
[BUG] Search Bar no longer works properly

### ISSUE THREAD

**Issue by MrAyytism** [AdamXweb/WhiteSurFirefoxThemeMacOS#130]
### Describe the problem

Hi, just got a Firefox update today and now when clicking the main searchbar, when typing anything all the results display all the way to the left so if cuts off the home/reload/traffic lights as shown. When nothign is typed is does look normal though
<img width="1792" alt="Screenshot 2024-11-26 at 16 35 41" src="https://github.com/user-attachments/assets/3feee5e2-922b-4cb4-8a43-bf2692f0fd90">
<img width="1794" alt="Screenshot 2024-11-26 at 16 35 58" src="https://github.com/user-attachments/assets/a75706ae-99a7-4f8a-b108-fc9d439a1c77">

### Version

1.5.6

### OS

15.1.1

### Firefox Version

133

### Install Options

none

### Colour Theme

no

### Please tick the boxes

- [X] You are using a [current](https://github.com/AdamXweb/WhiteSurFirefoxThemeMacOS/releases/) version of the theme. (check the date associated with the version)
- [X] You've checked that this [issue hasn't already been raised](https://github.com/adamxweb/WhiteSurFirefoxThemeMacOS/issues?q=is%3Aissue)

**Comment by AdamXweb** [comment]
@MrAyytism Thanks for submitting - I'll look into this!

**Comment by iyiolacak** [comment]
Same issue+

**Comment by AdamXweb** [comment]
<img width="1058" alt="image" src="https://github.com/user-attachments/assets/7518f9cd-69d6-410d-97cc-474b8066bf25">
fixed

**Comment by dbustosrc** [comment]
This bug was fixed in v133 and v134, but is still present in v135
