### ISSUE TITLE
[BUG] Maximise, Minimise, and Close buttons are missing after Firefox updated.

### ISSUE THREAD

**Issue by DetectiveAlice** [AdamXweb/WhiteSurFirefoxThemeMacOS#131]
### Describe the problem

as the title says, firefox updated and the window management buttons are gone. removed the theme and they're back. i tried reinstalling, and it didn't work.

it's a great theme, so i'm sad that it's not working. 

### Version

1.5.6

### OS

Windows 10

### Firefox Version

133.0

### Install Options

manual

### Colour Theme

no

### Please tick the boxes

- [X] You are using a [current](https://github.com/AdamXweb/WhiteSurFirefoxThemeMacOS/releases/) version of the theme. (check the date associated with the version)
- [x] You've checked that this [issue hasn't already been raised](https://github.com/adamxweb/WhiteSurFirefoxThemeMacOS/issues?q=is%3Aissue)

**Comment by AdamXweb** [comment]
Hi @DetectiveAlice, thanks for raising this issue - I'll look into this

**Comment by sajjad-salam** [comment]
me too  i have same problem 
![image](https://github.com/user-attachments/assets/71ee748b-bcfd-4c02-9807-42675f9315db)

**Comment by DetectiveAlice** [comment]
thanks for the quick reply. it's a cool theme!

**Comment by AdamXweb** [comment]
<img width="1437" alt="Screenshot 2024-12-01 at 9 44 15 PM" src="https://github.com/user-attachments/assets/30c1635c-13c0-4349-85cf-c010ea398082">
<img width="1440" alt="Screenshot 2024-12-01 at 9 43 47 PM" src="https://github.com/user-attachments/assets/a217c1ae-ffb0-4b39-994f-c271db396e6f">

Confirmed fix on both standard and windows swap close
