### ISSUE TITLE
[BUG] Close/Minimize/Maximize buttons are placed at the incorrect place

### ISSUE THREAD

**Issue by Serena1432** [AdamXweb/WhiteSurFirefoxThemeMacOS#132]
### Describe the problem

It's about the same as #131, however the buttons don't disappear; instead they're placed next to open tabs (as the image below) instead of next to the navigation buttons like usual.

Also, the URL textbox placement seems to be a bit off to the top (not properly centered).

### Version

1.5.6 (2024-10-27)

### OS

macOS 14.7.1

### Firefox Version

133.0

### Install Options

Manual installation

### Colour Theme

Default

### Additional info

![image](https://github.com/user-attachments/assets/53c5483b-fa0a-41aa-8d81-74752f6dcb57)

![image](https://github.com/user-attachments/assets/a61948cd-f141-4ff2-902c-1521d580442c)

### Please tick the boxes

- [x] You are using a [current](https://github.com/AdamXweb/WhiteSurFirefoxThemeMacOS/releases/) version of the theme. (check the date associated with the version)
- [X] You've checked that this [issue hasn't already been raised](https://github.com/adamxweb/WhiteSurFirefoxThemeMacOS/issues?q=is%3Aissue)

**Comment by MrAyytism** [comment]
Same for me... forgot to mention it in my post!

**Comment by AdamXweb** [comment]
<img width="331" alt="image" src="https://github.com/user-attachments/assets/39fe4753-9c62-4f2c-b2cf-f19ba0c1d627">
fixed
