### ISSUE TITLE
[BUG] Tabs missing close button at a certain width and the font in tabs is default (times new roman) 

### ISSUE THREAD

**Issue by matthewjflee** [AdamXweb/WhiteSurFirefoxThemeMacOS#135]
### Describe the problem

1. Once you get to a certain number of tabs, hovering over a non-active tab no longer displays the "x" button to close the tab. This could be a Firefox issue and not a CSS theme issue
2. After the update to v1.6, the font for tabs seem to no longer be applied. It looks like it is Times New Roman
<img width="312" alt="Screenshot 2024-12-10 at 00 17 39" src="https://github.com/user-attachments/assets/83f9be2d-50e4-402f-a4f2-24cd9c11b643">

Thank you so much for this theme! I honestly love using it.

### Version

v1.6 2024-12-01

### OS

macOS 15.1.1

### Firefox Version

133.0

### Install Options

-c

### Colour Theme

default. I didn't know you could have other colour options

### Please tick the boxes

- [X] You are using a [current](https://github.com/AdamXweb/WhiteSurFirefoxThemeMacOS/releases/) version of the theme. (check the date associated with the version)
- [X] You've checked that this [issue hasn't already been raised](https://github.com/adamxweb/WhiteSurFirefoxThemeMacOS/issues?q=is%3Aissue)

**Comment by zhen737** [comment]
Can confirm the font issue occurs in **Windows** as well.

Version: v1.6 2024-12-01 
OS: Windows 11
Firefox Version: 133.0 (64-bit)

![Screenshot 2024-12-10 170134](https://github.com/user-attachments/assets/4faf7010-47e4-4840-ad5e-0cf2319e13b5)

**Comment by joonaskokko** [comment]
Having exactly the same problem (macOS 15.1.1). I think it started just now, been using v1.6 for a while and I think the fonts worked correctly in the beginning. Very odd.

**Comment by joonaskokko** [comment]
Also in my testing the tab/window widths don't seem to have any affect.

![Screenshot 2024-12-16 at 11 45 49](https://github.com/user-attachments/assets/f8420aad-0fe1-4f9a-bf99-2e8d975940b2)

**Comment by Minecraft633** [comment]
Change default font

**Comment by joonaskokko** [comment]
> Change default font

Thanks! This is a great temporary workaround!

**Comment by AdamXweb** [comment]
both fixed in v1.6.1, please let me know if any further issues pop up

**Comment by JuenTingShie** [comment]
hi !
After [v1.6.1](https://github.com/AdamXweb/WhiteSurFirefoxThemeMacOS/commits/v1.6.1), pinned tab look messy i think

top image is v1.6.0, bottom is v1.6.1
![圖片](https://github.com/user-attachments/assets/1e2248eb-1bdf-47ed-8046-0c457ca4ee0d)



close button is always shown on pinned tab.
