### ISSUE TITLE
[BUG] Container Pinned Tabs Disappear

### ISSUE THREAD

**Issue by Chris111212** [AdamXweb/WhiteSurFirefoxThemeMacOS#14]
**Describe the bug**
Pinned tabs disappear on Windows

**To Reproduce**
Pin a tab in a container and it disappears

**Expected behavior**
To see the pinned tab on the left side of the screen

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser Firefox
 - Version 88.0.1

**Comment by AdamXweb** [comment]
Can confirm have reproduced the bug on MacOS also. I'll look into it

**Comment by AdamXweb** [comment]
<img width="192" alt="Screen Shot 2021-05-07 at 2 15 15 pm" src="https://user-images.githubusercontent.com/6800453/117397068-a66e1f00-af3e-11eb-8a62-44dd7eb65cb5.png">
Can confirm working on Macos v88.0.1

**Comment by AdamXweb** [comment]
<img width="196" alt="Screen Shot 2021-05-07 at 3 06 50 pm" src="https://user-images.githubusercontent.com/6800453/117400409-e7b5fd00-af45-11eb-8a92-cb7f57639fc2.png">
Changes also work on Windows
