### ISSUE TITLE
[FEAT] Change the left corner controls

### ISSUE THREAD

**Issue by Chris111212** [AdamXweb/WhiteSurFirefoxThemeMacOS#15]
**Describe the solution you'd like**
The corner should be close, minimize, maximize. On Windows currently it is minimize, maximize, close
How it is
![image](https://user-images.githubusercontent.com/83782624/117494002-b6d3c900-af41-11eb-9d40-6c6da7856cbe.png)
How it should be
![tOOjs](https://user-images.githubusercontent.com/83782624/117494035-c521e500-af41-11eb-88a7-e9b65f9a03fb.png)

**Comment by AdamXweb** [comment]
I'll look into this!

**Comment by AdamXweb** [comment]
https://github.com/AdamXweb/WhiteSurFirefoxThemeMacOS/commit/9ab0072bb9b826948302bf1ff5d99fb573e8252e

**Comment by AdamXweb** [comment]
![image](https://user-images.githubusercontent.com/6800453/117522539-674fd480-aff7-11eb-9edc-c61e057135f8.png)
Fixed ordering.

![image](https://user-images.githubusercontent.com/6800453/117522544-7171d300-aff7-11eb-8dff-9f45a0156984.png)
Also fixed the background hover that looked un-natural
