### ISSUE TITLE
[BUG] Can't give FF permission to share screen

### ISSUE THREAD

**Issue by chadstur** [AdamXweb/WhiteSurFirefoxThemeMacOS#16]
When accessing the web apps of Google Meet and Webex (haven't tried Zoom or Teams) and trying to share screen, I'm unable to click "Allow" button when prompted. Works fine when I remove this custom theme.

- Using 1.1.3
- Firefox 88.0.1
- 16" MacBook Pro running 11.3.1
<img width="514" alt="Screen Shot 2021-05-07 at 11 37 07 AM" src="https://user-images.githubusercontent.com/57020782/117494351-0fe33300-af29-11eb-8cd0-728c5078ed4b.png">

**Comment by AdamXweb** [comment]
<img width="537" alt="Screen Shot 2021-05-08 at 11 40 13 am" src="https://user-images.githubusercontent.com/6800453/117521671-56509480-aff2-11eb-8053-157bb754dc7b.png">
Bug was based on missing styling for disabled allow button. Text showing `select window or screen` was missing styling to indicate it is a dropdown.
<img width="526" alt="Screen Shot 2021-05-08 at 11 40 23 am" src="https://user-images.githubusercontent.com/6800453/117521677-58b2ee80-aff2-11eb-8bc5-3bc37394b6e6.png">
Has now been fixed for better UX
Tested in light and dark mode to be working
