### ISSUE TITLE
would it be possible to remove the color of container line for above each tab

### ISSUE THREAD

**Issue by Parthvsquare** [AdamXweb/WhiteSurFirefoxThemeMacOS#18]
![image](https://user-images.githubusercontent.com/26404957/117541508-d3e7c500-b031-11eb-9f2a-3e821afa87b5.png)
The current setup 
![image](https://user-images.githubusercontent.com/26404957/117541553-05609080-b032-11eb-955a-8898e75745c4.png)
This is how safari looks like
---
Using on catalina .15.7

**Comment by Chris111212** [comment]
or do a colored dot for each container?

**Comment by AdamXweb** [comment]
It's definitely possible, however may come down to user preference.
Seeing as on Firefox, the multi tab container is a feature Safari doesn't have I'd argue that colour of some kind should be there.
You can add the following code into your customChrome.css (if you don't have one, make one in the same `chrome` folder.

`.tabbrowser-tab[usercontextid] > .tab-stack > .tab-background {
    border-top: 3px solid transparent !important;
}`

**Comment by AdamXweb** [comment]
Also for reference, these are the standard identity colour locations that Firefox supports.
![image](https://user-images.githubusercontent.com/6800453/117557407-e277c000-b0b5-11eb-874b-9db28702b787.png)
Could always have some kind of vote, or a script that can change the location as it may come down to user preference.
