### ISSUE TITLE
Horizontal window line too bright and large

### ISSUE THREAD

**Issue by chadstur** [AdamXweb/WhiteSurFirefoxThemeMacOS#19]
Hello, this is nit picky but noticeable: the horizontal line on this Safari theme is too bright compared to raw Safari. Please see attached screenshot contrasting Firefox in background with Safari in foreground. 
<img width="950" alt="Screen Shot 2021-05-09 at 7 56 52 PM" src="https://user-images.githubusercontent.com/57020782/117600759-6d31dc80-b101-11eb-9302-d98eb9cfb9e0.png">

**Comment by AdamXweb** [comment]
I see it now also... May be a Firefox specific bug, as without the theme it still seems to be displayed in dark mode..
We may need more help from the community for this one
<img width="122" alt="Screen Shot 2021-05-10 at 3 27 18 pm" src="https://user-images.githubusercontent.com/6800453/117612492-a3766700-b1a8-11eb-962c-ae8616ac8aaf.png">

**Comment by AdamXweb** [comment]
https://bugzilla.mozilla.org/show_bug.cgi?id=1575070
This has been marked as resolved by Mozilla for V91 and v92
