### ISSUE TITLE
Firefox Developer Edition support

### ISSUE THREAD

**Issue by ronilaukkarinen** [AdamXweb/WhiteSurFirefoxThemeMacOS#20]
Hello! On Firefox Developer Edition (89.0b10 (64-bit)) tabs look kinda weird:

![Screen-Shot-2021-05-11-09-54-27 04](https://user-images.githubusercontent.com/1534150/117771701-09153280-b23f-11eb-976e-48b5dc5f82d8.png)

Could you add support for this browser version as well?

**Comment by AdamXweb** [comment]
<img width="476" alt="Screen Shot 2021-05-12 at 2 16 35 am" src="https://user-images.githubusercontent.com/6800453/117849940-2b06c780-b2c8-11eb-8f55-69f2ba84203b.png">
Have fixed tab spacing. All that's left seems to be to style the right click menu. I haven't set a new release, however you may download the repo and update to test the changes

**Comment by AdamXweb** [comment]
5d0f09a9072f65041f8f44b71bd41a519d1ae007

**Comment by AdamXweb** [comment]
For future reference, if you'd like the custom styleing on the right click menu, the setting to add is this: `widget.macos.native-context-menus = false`
