### ISSUE TITLE
Not the entire url bar is "clickable" to edit[BUG]

### ISSUE THREAD

**Issue by Retr01997** [AdamXweb/WhiteSurFirefoxThemeMacOS#23]
**Describe the bug**
Not the entire url bar is actually responding to clicks. The text seems to cut of at around the 3/4 mark and beyond that clicking on the url bar doesn't allow for editing the url. And the first 1/4 has the same issue (see screenshot)

**To Reproduce**
1. open firefox
2. go to any website
3. click anywhere on url bar where there is no text

**Expected behavior**
Clicking anywhere in the url bar that is not a button with a specific function (eg. 3dot menu or favorites button) to start editing the url.

**Screenshots**
![image](https://user-images.githubusercontent.com/68734666/118361104-2113eb80-b58a-11eb-94a6-83bef16e2532.png)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Firefox version 88.0.1
 - WhiteSur theme v1.1.4

**Comment by AdamXweb** [comment]
I've added an option on the install to centre the text like safari, and to have the ability to click anywhere on the URL bar
<img width="357" alt="Screen Shot 2021-05-17 at 8 29 56 pm" src="https://user-images.githubusercontent.com/6800453/118474661-a5af6700-b74e-11eb-8304-0adce6ce3e6f.png">
