### ISSUE TITLE
Tab title not centered when playing media

### ISSUE THREAD

**Issue by cloudslash7** [AdamXweb/WhiteSurFirefoxThemeMacOS#25]
The title on the tab right-justified when any media is playing. Tested on YouTube and Coursera.

<img width="772" alt="Screen Shot 2021-05-17 at 1 43 05 PM" src="https://user-images.githubusercontent.com/62630455/118554243-0ec6b880-b716-11eb-8506-682d110314ca.png">

**Comment by AdamXweb** [comment]
What OS are you using, browser version and theme version?
I can't seem to replicate the bug..
<img width="857" alt="Screen Shot 2021-05-18 at 7 48 48 am" src="https://user-images.githubusercontent.com/6800453/118560850-7d0a8a00-b7ad-11eb-96dd-b532abcbd4ed.png">

**Comment by cloudslash7** [comment]
@AdamXweb Hmm...I am using Firefox Nightly so that may be the problem. I'll try on stable. I'm running 11.3.1, latest theme version

**Comment by AdamXweb** [comment]
> @AdamXweb Hmm...I am using Firefox Nightly so that may be the problem. I'll try on stable. I'm running 11.3.1, latest theme version
> 
> EDIT:
> Yeah, works fine on stable, unsurprisingly haha. I'm not sure what could've caused that behavior though!

Seems with 'Proton' (name of new update) they added new items into the centred content of the container which is causing it to be pushed over to the side. Have confirmed that this issue also affects the Developer Edition.

I'll get round to fixing it in the next few weeks!

**Comment by cloudslash7** [comment]
Ahh I didn’t realize Proton hadn’t hit stable yet. I’ll use stable for now, then. Thank you for the awesome theme! 👍

**Comment by AdamXweb** [comment]
5d0f09a9072f65041f8f44b71bd41a519d1ae007

**Comment by AdamXweb** [comment]
<img width="800" alt="Screen Shot 2021-05-30 at 2 14 58 pm" src="https://user-images.githubusercontent.com/6800453/120091762-6b33ca00-c151-11eb-916e-9c693de66aac.png">
Fix now working and ready
