### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by zohaad** [AdamXweb/WhiteSurFirefoxThemeMacOS#28]
**Describe the bug**
Clicking in the address bar doesn't go into edit mode

**To Reproduce**
click *next* to the address

**Expected behavior**
go into edit mode 

**Desktop (please complete the following information):**
 - OS: macOS 11.3.1
 - Firefox version 88
 - WhiteSur theme 1.2.2
 - Any options added during installation N/A

**Comment by AdamXweb** [comment]
Please try installing again with the flag `-u`

**Comment by AdamXweb** [comment]
the full command would be: `bash install.sh -u`
