### ISSUE TITLE
[BUG] Inactive tab has translucency

### ISSUE THREAD

**Issue by mciarlo** [AdamXweb/WhiteSurFirefoxThemeMacOS#29]
**Describe the bug**
After uninstalling all theming plugins and reverting to the default theme, the inactive tabs don't appear to use opaque colors.

**To Reproduce**
1. Install theme version 1.2.2
2. Restart Firefox
3. Observe inactive tabs and the "+" tab button have macOS style translucency.

**Expected behavior**
The tabs are opaque.

**Screenshots**
<img width="811" alt="Screen Shot 2021-05-18 at 7 55 47 PM" src="https://user-images.githubusercontent.com/378406/118737713-6f87eb00-b813-11eb-98e7-97dd4d9dd8c5.png">

**Desktop (please complete the following information):**
 - OS: macOS 10.15.7
 - Firefox version 88.01
 - WhiteSur theme 1.2.2
 - Installed by dragging the folders to my profile folder

**Comment by AdamXweb** [comment]
I'll look into making a permanent fix, however the best option is to choose the dark theme that comes with Firefox. This'll allow the theme to look like how it was shown!

**Comment by AdamXweb** [comment]
May also have another example on [Reddit](https://www.reddit.com/r/FirefoxCSS/comments/n54djs/safari_big_sur_theme_for_firefox_on_macos/gynuyhl?utm_source=share&utm_medium=web2x&context=3)

**Comment by AdamXweb** [comment]
<img width="1713" alt="Screen Shot 2021-05-30 at 3 03 15 pm" src="https://user-images.githubusercontent.com/6800453/120092675-2d866f80-c158-11eb-97f6-dc82aa019907.png">
bb2b7d757c2fb6f4c79d97977e099d19ea7f7edf
