### ISSUE TITLE
No dark theme?

### ISSUE THREAD

**Issue by Ryan-da-ghost** [AdamXweb/WhiteSurFirefoxThemeMacOS#3]
Please provide a dark theme!!

**Comment by AdamXweb** [comment]
The current way the theme is setup is to obey the system's "light" or "dark" mode.
I'll look into being able to set the theme colours outside of system defaults, however that may need a complete re-work.

**Comment by AdamXweb** [comment]
The solution if you don't want to change your System UI colour is to do add the following to your `about:config`
Add: `ui.systemUsesDarkTheme` with the number value with 1 for dark, and 0 for light.
![Screen Shot 2021-05-04 at 7 10 19 pm](https://user-images.githubusercontent.com/6800453/116982626-60317980-ad0c-11eb-96aa-0879b05c98fc.png)
