### ISSUE TITLE
Change fonts and bookmarks label color

### ISSUE THREAD

**Issue by arshsaxena** [AdamXweb/WhiteSurFirefoxThemeMacOS#30]
What should I edit to change font style and color of bookmarks label?

**Comment by AdamXweb** [comment]
Can you take a screenshot about what you're referring to?

**Comment by arshsaxena** [comment]
![screenshot](https://user-images.githubusercontent.com/66147853/119076858-ee964280-ba10-11eb-9e56-b9d5db590c1b.PNG)
Font style of URL and color of bookmarks label.

**Comment by AdamXweb** [comment]
<img width="311" alt="Screen Shot 2021-05-21 at 1 19 03 pm" src="https://user-images.githubusercontent.com/6800453/119077144-1ef0d780-ba37-11eb-8f1a-2ab1998dcb86.png">
This is how it looks for myself.
Do you have the inbuilt Firefox Dark theme selected?
Sometimes that overwrites whatever I've put in the theme.

Also, what OS & firefox version are you using?

**Comment by arshsaxena** [comment]
Thanks! Bookmarks label color is fine now. What about font style?

**Comment by AdamXweb** [comment]
```
toolbarbutton.bookmark-item{
font-weight:bold;
}
```

**Comment by arshsaxena** [comment]
Not that, I am asking for font-family of URL and bookmarks label.

**Comment by AdamXweb** [comment]
> Not that, I am asking for font-family of URL and bookmarks label.

I'm sorry, I don't think I understand what you are referring to then. The code:

> ```
> toolbarbutton.bookmark-item{
> font-weight:bold;
> }
> ```

would change "Amazon" above to bold.
If you're after font-family, then you can add whatever you like into that CSS class

**Comment by arshsaxena** [comment]
Adding `font-family` in `toolbarbutton.bookmark-item` will do that?

**Comment by AdamXweb** [comment]
Correct. I'd look into a [CSS](https://www.w3schools.com/Css/css_font.asp) resource to find the types of properties you can put in for fonts.
Just be careful if you're referencing a font that isn't built into the system e.g. Google fonts, as they'd have to be imported first.

**Comment by arshsaxena** [comment]
Okay, I will try and let you know.

**Comment by arshsaxena** [comment]
It worked! Where to make changes for changing font-family of URL bar and settings menu?

**Comment by AdamXweb** [comment]
If you're looking to learn, I suggest you read this:
https://www.reddit.com/r/FirefoxCSS/comments/73dvty/tutorial_how_to_create_and_livedebug_userchromecss/
