### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by Retr01997** [AdamXweb/WhiteSurFirefoxThemeMacOS#32]
**Describe the bug**
Minimize, maximize and close buttons not showing properly on Linux

**To Reproduce**
1. Install theme on Firefox for Linux
2. Look at minimize, maximize and close buttons

**Expected behavior**
Buttons to be better aligned and having the sadari style (green, yellow and red circle) 

**Screenshots**
I![image](https://user-images.githubusercontent.com/68734666/119631383-22f27000-be10-11eb-8769-8d7dc68f76ca.png)

**Desktop (please complete the following information):**
 - OS: [Ubuntu 20.04.2 LTS]
 - Firefox version [88.0.1]
 - WhiteSur theme [v1.2.2]
 - Any options added during installation [-l (but same problem occurs with manual install)]

**Comment by AdamXweb** [comment]
I'd recommend trying this theme if you're using linux: https://github.com/vinceliuice/WhiteSur-gtk-theme/tree/master/src/other/firefox
