### ISSUE TITLE
[BUG] not able to apply theme

### ISSUE THREAD

**Issue by midtoan** [AdamXweb/WhiteSurFirefoxThemeMacOS#33]
**Describe the bug**
Firefox v89
- executed bash install.sh and followed the prompt. 
- toggled toolkit.legacyUserProfileCustomizations.stylesheets to 'true'
- manually installed theme 
- MacOS 10.15.7
- Firefox v89
- WhiteSur theme 1.3.0
- 
<img width="1113" alt="Screen Shot 2021-06-03 at 11 14 50 pm" src="https://user-images.githubusercontent.com/85309495/120691311-d05f2680-c495-11eb-99e7-cad5d549c543.png">

However, firefox is still appearing as the default theme.

**Comment by midtoan** [comment]
no bug. user error.

**Comment by AdamXweb** [comment]
May I ask what the issue ended up being?

**Comment by midtoan** [comment]
I had multiple profile folders and the script installed the theme in the old profile folder.

**Comment by AdamXweb** [comment]
Right, that would make sense, especially for the script, as it installs into the first folder it finds. Glad you figured it out!
