### ISSUE TITLE
[FEAT] Disable Facebook Container highlighting

### ISSUE THREAD

**Issue by actonca** [AdamXweb/WhiteSurFirefoxThemeMacOS#38]
Apologies if there is an obvious fix, but is there anyway to incorporate ".tab-context-line{display:none}" into this theme? I tried to add it to my userChrome, which disabled the whole theme. I find the lines indicating Facebook/Instagram tabs make it tough to find the active tab immediately. Thanks for any help.

**Comment by AdamXweb** [comment]
I'll look into this as an option when installing.

**Comment by AdamXweb** [comment]
Option has now been added. You can install with the flag `-n` to remove the identity colours.

**Comment by actonca** [comment]
Just got around to installing it today - works great, appreciate it.
