### ISSUE TITLE
[Question] How can I move the close,minimize and maximize buttons to the left on windows?

### ISSUE THREAD

**Issue by Toadfield** [AdamXweb/WhiteSurFirefoxThemeMacOS#42]
I hate it that they are on the left,I want them on the right.

**Comment by Toadfield** [comment]
And also,can I switch the minimize and maximize buttons?

**Comment by AdamXweb** [comment]
To place the buttons on the right, you must include the custom css.
These are the following steps:

1. Copy `windows-swapclose.css` from the custom folder into the `chrome/WhiteSur/parts` folder
2. Add this line `@import "parts/windows-swapclose.css";` to import it into the theme on line 17 of `chrome/WhiteSur/theme.css`

Restart firefox and the close buttons should be on the right hand side. (They'll also be arranged in the normal windows order)

**Comment by AdamXweb** [comment]
For reference, this is what it'll look like after the next tweaked version v1.3.2
![image](https://user-images.githubusercontent.com/6800453/127331825-6bd0f169-e232-4220-9cc2-f918030f3b82.png)
