### ISSUE TITLE
[BUG] Tab bar gets smaller when dragging tabs

### ISSUE THREAD

**Issue by patrick6284** [AdamXweb/WhiteSurFirefoxThemeMacOS#45]
**Describe the bug**
Tab bar gets smaller when dragging tabs

**To Reproduce**
1. Click on a tab
2. Drag the tab
3. See error

**Expected behavior**
Tab should stay the same size

**Screenshots**
https://i.imgur.com/rsZPR0z.png

**Desktop (please complete the following information):**
 - OS: MacOS 11
 - Firefox version: 91.0.2
 - WhiteSur theme: 1.3.1
 - Any options added during installation [e.g. -c]: None

https://user-images.githubusercontent.com/86033251/131427773-9b3ac0e6-fd30-428a-bd04-d13f89413887.mov

**Comment by AdamXweb** [comment]
Thanks for submitting! I'll look into this

**Comment by AdamXweb** [comment]
Fixed!
