### ISSUE TITLE
[BUG] Firefox Crashes on 93.0b2 

### ISSUE THREAD

**Issue by unknown9258** [AdamXweb/WhiteSurFirefoxThemeMacOS#48]
**Describe the bug**
Firefox crashes when Whitesur theme is installed

**To Reproduce**
1. Install Firefox 93.0b2 (64-bit)
2. Open firefox after installation 
3. Error message saying firefox has crashed 
**Expected behavior**
It can open normally

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Firefox version 93.0b2 (64-bit)
 - WhiteSur theme  v1.1.3

**Comment by AdamXweb** [comment]
What was your method of installation? Did it include enabling stylesheets in settings prior?

I'm not on firefox nightly so haven't been able to test.

**Comment by unknown9258** [comment]
I installed it manually

**Comment by unknown9258** [comment]
I have enabled toolkit.legacyUserProfileCustomizations.stylesheets

**Comment by unknown9258** [comment]
Thanks, it is working in 93.0b3 now

**Comment by AdamXweb** [comment]
I wonder what was in b2 that stopped it from working..
