### ISSUE TITLE
[FEAT] Tree style tab extension keeps tab padding

### ISSUE THREAD

**Issue by GamerPlayer888** [AdamXweb/WhiteSurFirefoxThemeMacOS#51]
How do remove the tabs bar? I have hidden them because I prefer to use Tree Style Tab (like Safari on iPadOS 15), but it remains visible empty.
![image](https://user-images.githubusercontent.com/66787796/133108302-373601a2-8235-41d0-b617-c3488dd837c8.png)

The buttons for window are a little too small, and sometimes I miss click, how do I reset the default to Windows or make them bigger?

**Comment by AdamXweb** [comment]
It sounds like you have two questions:
For the first one, the following CSS code may fix your issue:
`#TabsToolbar{
 height:0px !important;
}
toolbar{
min-height: 0px !important;
}
`

To resize the menubar icons, you can edit the padding here:
https://github.com/AdamXweb/WhiteSurFirefoxThemeMacOS/blob/a6dad249809c45124e5ea0f060f06a710ea8d431/chrome/WhiteSur/parts/windows.css#L4-L12

You can follow these instructions to edit the browser live:
https://www.reddit.com/r/FirefoxCSS/comments/73dvty/tutorial_how_to_create_and_livedebug_userchromecss/
