### ISSUE TITLE
[FEAT] Tab close button fade

### ISSUE THREAD

**Issue by Faruolo2** [AdamXweb/WhiteSurFirefoxThemeMacOS#53]
I just added the code below to make tab close button fade in when hovering over the button:

.tabbrowser-tab:not([pinned]) .tab-close-button {
  display: -moz-box !important;
  opacity: 0;
  visibility: collapse !important;
  transition: all 0.2s ease-in !important;
}

.tabbrowser-tab:not([pinned]):hover .tab-close-button {
  opacity: 0.5;
  visibility: visible !important;
  transition: all 0.2s ease-in !important;
}

.tabbrowser-tab:not([pinned]) .tab-close-button:hover {
  opacity: 1.0;
  transition: opacity 0.2s ease-in !important;
}

i think it blends more natively to what Safari do.

If you could add this to the css :)

**Comment by examrange** [comment]
Hi, Is there any way you can make the "Close tab" button on left? 
Thank you

**Comment by AdamXweb** [comment]
@examrange You can import the custom css from custom/lhsclose.css to the theme.css file

**Comment by AdamXweb** [comment]
@Faruolo2 Thanks for the suggestion, have added the show only on hover with a few tweaks
