### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by unknown9258** [AdamXweb/WhiteSurFirefoxThemeMacOS#55]
**Describe the bug**
proton is breaking the custom the,e

**Screenshots**
![Screenshot 2021-12-20 013134](https://user-images.githubusercontent.com/77475477/146684778-c1500389-6e65-4feb-af9a-b95749cbbed3.jpg)

**Desktop (please complete the following information):**
 - OS Windows 10
 - Firefox version 96.0 b5
 - WhiteSur theme [e.g. v1.4]
 - Any options added during installation [e.g. -c]

**Comment by AdamXweb** [comment]
Firefox v96 seemed to break the moz-proton media query. Fix suggested by https://www.reddit.com/r/FirefoxCSS/comments/s5te1e/comment/hszppge/?utm_source=share&utm_medium=web2x&context=3
