### ISSUE TITLE
[BUG]Clicking folders in Bookmark toolbar doesnt have same UI like WhiteSur theme

### ISSUE THREAD

**Issue by SwiftyPop** [AdamXweb/WhiteSurFirefoxThemeMacOS#56]
**Describe the bug**
Clicking folders in Bookmark toolbar doesnt have same UI like WhiteSur theme. Can this be fixed?

**To Reproduce**
1. Show the bookmark toolbar
2. Click on folders
3. You will get the UI

**Expected behavior**
Have similar UI like the theme.

**Screenshots**
![image](https://user-images.githubusercontent.com/90952326/147804050-937e7823-7a92-40f5-b3eb-e66cd77fc5a3.png)

**Desktop:**
 - OS: Windows 10 20H2
 - Firefox version: Firefox 95.0.2

**Comment by AdamXweb** [comment]
A fix is underway

**Comment by AdamXweb** [comment]
Fix works on MacOS, however some transparency visible on Windows

**Comment by AdamXweb** [comment]
Related to #60
