### ISSUE TITLE
[BUG] Maximize, Minimize and close buttons bug

### ISSUE THREAD

**Issue by gleyzer17** [AdamXweb/WhiteSurFirefoxThemeMacOS#58]
It looks like a fusion. Two buttons together in the same place.

Is it a conflict with something?

![Captura de Tela (235)](https://user-images.githubusercontent.com/97526259/148947019-78fb2c6c-4257-4248-a25d-7fc5820d6628.png)

**Comment by AdamXweb** [comment]
What OS and firefox version are you using?

**Comment by AdamXweb** [comment]
Closing as no OS or version details provided
