### ISSUE TITLE
[BUG] Tabs looks weird not like screenshots do.

### ISSUE THREAD

**Issue by SwiftyPop** [AdamXweb/WhiteSurFirefoxThemeMacOS#59]
**Describe the bug**
Don't know if it's my issue or the theme but the tabs look a bit weird. Do you what the issue is?

**To Reproduce**
None.

**Expected behavior**
Tabs should be looking like this: 
![image](https://user-images.githubusercontent.com/90952326/149935714-4bc814bd-d8c4-41a1-8545-b674c3c0afdd.png)

**Screenshots**
![Tabskindaweirdmen](https://user-images.githubusercontent.com/90952326/149935775-b3c9abf9-d742-4eb5-a85e-f060d400509e.gif)

**Desktop (please complete the following information):**
 - OS: Windows 11 (Recently fresh install the OS)
 - Librewolf 96.1.1 (I don't think it Librewolf fault. Last time I use the browser was working fine back in 2021)
 - WhiteSur theme v1.4
 - Any options added during installation: none.

**Comment by AdamXweb** [comment]
Could you try the latest commit? (downloading the repo instead of the release) Firefox v96 changed some things, but I haven't tested the fix on Windows just yet

**Comment by AdamXweb** [comment]
Is there also an issue with the first screenshot's window control buttons?

**Comment by AdamXweb** [comment]
Tested working on Windows V96.0.
<img width="1731" alt="Screen Shot 2022-01-19 at 6 43 13 pm" src="https://user-images.githubusercontent.com/6800453/150086053-7d745905-37c4-4a24-b987-35f28cb25a25.png">
1

**Comment by AdamXweb** [comment]
If first screenshot was fullscreen mode, #6 has been fixed today also
