### ISSUE TITLE
[BUG] Windows 7 window controls don't show

### ISSUE THREAD

**Issue by etkest2** [AdamXweb/WhiteSurFirefoxThemeMacOS#61]
**buttons to close, open and shrink do not appear, and there are display bugs**

**To Reproduce**
1. open firefox
2. See error

**Expected behavior**
I expected to see the buttons showing up but they never appeared

**Screenshots**
![Capture](https://user-images.githubusercontent.com/100474566/155844439-a955b337-8726-4b5a-82e4-bb691707ec29.PNG)
![bogue 2](https://user-images.githubusercontent.com/100474566/155844652-ec788468-e6ed-43d3-9ff3-dace5ada7bef.PNG)
**Desktop**
 - OS: [Windows 7 Professionel x86]
 - Firefox version [97.0.1]
 - WhiteSur theme [latest version available]

**Additional context**
you will notice that there are also display bugs on the search bar and other elements

**Comment by AdamXweb** [comment]
I'm not too sure about Windows 7 and how they use the 'Windows Aero' for window management.
Did you have another OS to test, as I don't think i'll be able to replicate the issue at all.

**Comment by AdamXweb** [comment]
No response, OS unsupported - closing issue
