### ISSUE TITLE
[BUG] Windows maximize button size not consistent

### ISSUE THREAD

**Issue by gayfieri** [AdamXweb/WhiteSurFirefoxThemeMacOS#63]
**Describe the bug**
maximize button is bigger than the other two when hovered over

**To Reproduce**
hover over titlebar buttons

**Expected behavior**
maximize button stays the same size, with a slight dark border around it

**Screenshots**
https://i.imgur.com/clZOawE.mp4
https://i.imgur.com/p0wqkAC.png

**Desktop (please complete the following information):**
 - OS: Windows 10 21H2, build 19044
 - Firefox version: 97.0.2
 - WhiteSur theme: v1.4.1

**Comment by AdamXweb** [comment]
Is this when the window is maximised, in full screen mode or windowed?

**Comment by gayfieri** [comment]
maximized

**Comment by AdamXweb** [comment]
https://user-images.githubusercontent.com/6800453/160052521-c925ab4e-9098-47a6-b580-f1972c615f43.mov

Issue not evident in firefox v99
Have fixed for current v98, confirmed fix will carryover to v99
doesn't effect macos.
