### ISSUE TITLE
[BUG] Windows 11 Firefox Beta v99 titlebar buttons not styled correctly

### ISSUE THREAD

**Issue by unknown9258** [AdamXweb/WhiteSurFirefoxThemeMacOS#64]
Describe the bug
The titlebar buttons is not styled correctly  firefox 99.0b1

To Reproduce
apply theme in firefox nightly

Expected behaviour
It should look normal

**Screenshots**
![image](https://user-images.githubusercontent.com/77475477/157640418-f4c78320-64a0-4d9b-af10-17f35264b1fd.png)

**Desktop (please complete the following information):**
 - OS: Windows 11 21H1 (Build 22000.556)
 - Firefox version 99.0b1
 - WhiteSur theme  v1.4.1

**Comment by AdamXweb** [comment]
<img width="862" alt="Screen Shot 2022-03-10 at 9 41 59 pm" src="https://user-images.githubusercontent.com/6800453/157645232-661f0b3c-4aab-4cc4-9099-a58c1fea172c.png">
Looks like a windows only issue. Will investigate further

**Comment by satanphobia** [comment]
Also experiencing this bug, Windows 11 with Firefox Beta.
Enabling the Title Bar fixes it temporarily/makes the theme usable.
There's some Reddit posts about it [here](https://www.reddit.com/r/FirefoxCSS/comments/tcg5qe/firefox_whitesur_theme_malfunctioned_on_firefox/i0mh6k5/?context=3) and [here](https://www.reddit.com/r/FirefoxCSS/comments/tdfvhh/whitesur_firefox_theme_all_glitched_up_after/).

**Comment by AdamXweb** [comment]
After investigating, found the media query for moz-os-version: windows-10 was being overidden by:
`-moz-windows-compositor`
Have updated, and is compatible with ff developer, 
![Screen Shot 2022-03-23 at 12 50 48 pm](https://user-images.githubusercontent.com/6800453/159606380-8aff64c4-aa0f-4e3d-bb71-4def51fbbd3c.png)

and current windows ff
![Screen Shot 2022-03-23 at 12 46 46 pm](https://user-images.githubusercontent.com/6800453/159606367-edcd56a5-478f-4716-8ee1-740d187ec5f8.png)


Also for those wondering how the icons are on the right, you can add the windows-swapclose.css to the theme.css
![Screen Shot 2022-03-23 at 12 55 35 pm](https://user-images.githubusercontent.com/6800453/159606683-c9494335-ee7e-4e9f-a396-62d9426ac91b.png)
And copy the custom folder into the WhiteSur folder.

**Comment by Toniolo-Marco** [comment]
> After investigating, found the media query for moz-os-version: windows-10 was being overidden by: `-moz-windows-compositor` Have updated, and is compatible with ff developer, ![Screen Shot 2022-03-23 at 12 50 48 pm](https://user-images.githubusercontent.com/6800453/159606380-8aff64c4-aa0f-4e3d-bb71-4def51fbbd3c.png)
> 
> and current windows ff ![Screen Shot 2022-03-23 at 12 46 46 pm](https://user-images.githubusercontent.com/6800453/159606367-edcd56a5-478f-4716-8ee1-740d187ec5f8.png)
> 
> Also for those wondering how the icons are on the right, you can add the windows-swapclose.css to the theme.css ![Screen Shot 2022-03-23 at 12 55 35 pm](https://user-images.githubusercontent.com/6800453/159606683-c9494335-ee7e-4e9f-a396-62d9426ac91b.png) And copy the custom folder into the WhiteSur folder.

Actually I'm facing this bug right now, on manjaro (22.0.0), firefox (104.0.2). I'm sorry but I don't really know how to get the version of the theme; should I open a new issue? I can attach screenshot here if needed.
