### ISSUE TITLE
[FEAT] Toolbar Firefox account Icon needs to be resized

### ISSUE THREAD

**Issue by unknown9258** [AdamXweb/WhiteSurFirefoxThemeMacOS#71]
**Describe the solution you'd like**
Shrink the size of Firefox account icon on the toolbar to make it look like the one without WhiteSur theme

![image](https://user-images.githubusercontent.com/77475477/160486482-a4524f0c-1903-4066-b838-63dcaea04e50.png)

**Comment by AdamXweb** [comment]
<img width="93" alt="Screen Shot 2022-03-29 at 10 16 30 pm" src="https://user-images.githubusercontent.com/6800453/160599666-684a630e-238b-4302-b4ca-6f570ee77d30.png">

Hi, just to confirm that you're talking about this profile image?
I don't use a firefox account so haven't seen this issue before

**Comment by unknown9258** [comment]
> <img alt="Screen Shot 2022-03-29 at 10 16 30 pm" width="93" src="https://user-images.githubusercontent.com/6800453/160599666-684a630e-238b-4302-b4ca-6f570ee77d30.png">
> 
> Hi, just to confirm that you're talking about this profile image? I don't use a firefox account so haven't seen this issue before

Yes Thanks
