### ISSUE TITLE
[BUG] The padlock icon on the address bar shows locked on insecure/HTTP websites

### ISSUE THREAD

**Issue by vazbloke** [AdamXweb/WhiteSurFirefoxThemeMacOS#74]
**Describe the bug**
The theme displays the padlock icon even when on an HTTP only page (proceeding to access the site after Firefox warns about it)
This gives the false impression that connection is secure, and could lead users to perform a transaction etc without thinking twice about it. Since the icon is what most people look at before sending / exchanging any sensitive data

**To Reproduce**
1. Go to any HTTP only website. Example: http://silent.org.pl/home/2022/06/13/the-floppotron-3-0/
2. Proceed to access despite the Firefox warning
3. The Padlock icon would be displayed as locked. Clicking on it reveals that the connection isn't secure

**Expected behavior**
The icon shows an a cross across the icon (or an exclamation point) to indicate the connection is not secure

**Screenshots**
<img width="345" alt="image" src="https://user-images.githubusercontent.com/7955976/173670977-b03ca371-fae5-4958-9711-a86c5f7ba631.png">

**Desktop (please complete the following information):**
 - OS: MacOS 12.4
 - Firefox version 101.0.1
 - WhiteSur theme: commit 392cf013e5a752725e569308e3b9db4a3d29408d

**Comment by AdamXweb** [comment]
Good pickup. I'll look into this ASAP

**Comment by AdamXweb** [comment]
<img width="596" alt="Screen Shot 2022-06-16 at 2 30 11 pm" src="https://user-images.githubusercontent.com/6800453/173991591-e30babb1-1dc2-4094-ab39-ab089627c4b3.png">
Added new icons for pages that are insecure as well as other warnings.

**Comment by vazbloke** [comment]
That was quick! Much appreciated
