### ISSUE TITLE
[BUG] Titlebar buttons not fully round in Windows 11

### ISSUE THREAD

**Issue by dannylol19** [AdamXweb/WhiteSurFirefoxThemeMacOS#79]
### Describe the problem

The titlebar buttons look more like polygons rather than circles.

### Version

1.4.4

### OS

Windows 11 Pro 10.0.22623

### Firefox Version

106.0.5

### Install Options

none

### Colour Theme

none

### Additional info

How it looks for me:
![image](https://user-images.githubusercontent.com/83356017/200198727-4f61f271-75e2-4982-a748-3f0470ccff2a.png)

How it's supposed to look:
![image](https://user-images.githubusercontent.com/83356017/200198774-e5234f2e-56fc-4577-9560-42a98c58fc23.png)

### Please tick the boxes

- [X] You are using a [current](https://github.com/AdamXweb/WhiteSurFirefoxThemeMacOS/releases/) version of the theme. (check the date associated with the version)
- [X] You've checked that this [issue hasn't already been raised](https://github.com/adamxweb/WhiteSurFirefoxThemeMacOS/issues?q=is%3Aissue)

**Comment by AdamXweb** [comment]
@dannylol19 Thanks for raising this issue!
I haven't been using Windows as often and the v106 update has broken quite a few visual bits.
Will look into
