### ISSUE TITLE
[BUG] The close/max/min icon is not align to system icons.

### ISSUE THREAD

**Issue by linitfor** [AdamXweb/WhiteSurFirefoxThemeMacOS#81]
### Describe the problem

Hi Developer,
My Firefox version. 108.0.1.
I have try to install your WhiteSurFirefoxThememMaxOS. It is pretty. But the icons seem not align to system icon.
How can I tune the position which can make the theme more accessible ?

![圖片](https://user-images.githubusercontent.com/58168507/209495296-8c9d085d-05ad-4697-991d-19a0f797d3a7.png)

### Version

1.4.4

### OS

Windows 11

### Firefox Version

108.0.1

### Install Options

manual install

### Colour Theme

no 

### Please tick the boxes

- [X] You are using a [current](https://github.com/AdamXweb/WhiteSurFirefoxThemeMacOS/releases/) version of the theme. (check the date associated with the version)
- [X] You've checked that this [issue hasn't already been raised](https://github.com/adamxweb/WhiteSurFirefoxThemeMacOS/issues?q=is%3Aissue)

**Comment by linitfor** [comment]
I found that I can custom the setting. 
![圖片](https://user-images.githubusercontent.com/58168507/209499946-623d35d1-2d3f-4a22-a757-9dde0d05b671.png)

**Comment by AdamXweb** [comment]
Hi @linitfor , thanks for submitting this issue! I'll reopen this as it will still affect others and needs to be updated in the theme. 
Cheers for submitting the resolution!
-AdamXweb

**Comment by linitfor** [comment]
Thank for your concern. 
The system icons mis-align might arised from the extend plugin icon on the main browser bar is larger than before.
If I hide all the plugin icons, I can have the beautiful firefox theme the same as which build from you.
![image](https://user-images.githubusercontent.com/58168507/209630469-28f84460-ab2c-465f-9c3b-11c17c4c06bf.png)

Hope you can modify for this issue. We can get more convenient tool experience.

By the way. Do you plan to bulid the mac safari theme support windows 11 mica effect ?

The other developer build mica theme like this.
![image](https://user-images.githubusercontent.com/58168507/209631199-e666609c-2eea-4522-b258-40edec115a6a.png)
