### ISSUE TITLE
[BUG] Install flags not working for release v1.5 for M1 Macs

### ISSUE THREAD

**Issue by maxwolv** [AdamXweb/WhiteSurFirefoxThemeMacOS#84]
### Describe the problem

Hi, install flags are not registering during install for M1 Macs. I tried the basic "bash install.sh -c" on multiple devices, and the close button was on the right. I also experimented with multiple flags, such as "-c -u", which still did nothing.

### Version

1.5

### OS

macOS 13.1

### Firefox Version

109

### Install Options

-c, -c -u, -c -f

### Colour Theme

n/a

### Please tick the boxes

- [X] You are using a [current](https://github.com/AdamXweb/WhiteSurFirefoxThemeMacOS/releases/) version of the theme. (check the date associated with the version)
- [X] You've checked that this [issue hasn't already been raised](https://github.com/adamxweb/WhiteSurFirefoxThemeMacOS/issues?q=is%3Aissue)

**Comment by AdamXweb** [comment]
Thanks for submitting this issue!
Could you please test this latest release which is based on the most recent commit:
https://github.com/AdamXweb/WhiteSurFirefoxThemeMacOS/releases/tag/v1.5.1

**Comment by AdamXweb** [comment]
Before jumping into specifics diagnosing this issue, could you please confirm if the script created the `custom` folder in the Firefox profile. You can access it by typing `about:support` into the URLbar and clicking 
<img width="277" alt="Screen Shot 2023-01-31 at 3 10 09 pm" src="https://user-images.githubusercontent.com/6800453/215660868-29d99c40-25db-4e28-a80a-36a52e28ee5f.png">
Testing to see if it has a folder named `custom` inside the `WhiteSur` folder.
<img width="234" alt="Screen Shot 2023-01-31 at 3 09 32 pm" src="https://user-images.githubusercontent.com/6800453/215660791-c26e343b-b4c8-4f2d-8183-2dfb7fb23273.png">
If not, then you could try the [latest commit](https://github.com/AdamXweb/WhiteSurFirefoxThemeMacOS/commit/47e4078214370a30ad464b9bb00edda0cebb2939)? This forces the folder to be stored in Git to avoid this issue.

**Comment by maxwolv** [comment]
The custom folder is not being created, here is an example of an error that shows in Terminal when running bash install.sh

**[action]: ⇒ Installing WhiteSur Firefox theme to your directory below
/Users/<USER>/Library/Application Support/Firefox/Profiles/*default-release /Users/<USER>/Library/Application Support/Firefox/Profiles/sisln89p.default-release
Enabling Tab close button on Left hand side
cp: /Users/<USER>/Library/Application Support/Firefox/Profiles/*default-release/chrome/WhiteSur/custom: No such file or directory**

This was tried with the latest commit, v1.5.1.

I believe that you are targeting the correct folder (Application Basics>Profile Folder) for initial transfer of the new theme, which is located at ".../Profiles/sisln89p.default-release", but then trying to install the modified css flags at location ".../Profiles/*default-release", without the "sisln89p." before it.

**Comment by AdamXweb** [comment]
Can you try placing a folder called custom inside the git repository inside the WhiteSur folder?

**Comment by maxwolv** [comment]
hi, downloading the latest commit works!
