### ISSUE TITLE
[BUG] Single tab view (-s flag on install) broken with Firefox 110

### ISSUE THREAD

**Issue by maxwolv** [AdamXweb/WhiteSurFirefoxThemeMacOS#85]
### Describe the problem

The single tab view, which hides the tab when a single tab is in use, is no longer working with Firefox 110. Reinstalling White Sur theme does not fix it, and this can be replicated by re-installing Firefox 109.

### Version

1.5.1

### OS

macOS 13.2.1

### Firefox Version

110

### Install Options

-c -s -n -e

### Colour Theme

n/a

### Please tick the boxes

- [X] You are using a [current](https://github.com/AdamXweb/WhiteSurFirefoxThemeMacOS/releases/) version of the theme. (check the date associated with the version)
- [X] You've checked that this [issue hasn't already been raised](https://github.com/adamxweb/WhiteSurFirefoxThemeMacOS/issues?q=is%3Aissue)

**Comment by AdamXweb** [comment]
Thanks for reporting the issue!
I'll look into this to patch the update

**Comment by AdamXweb** [comment]
Fixed in latest commit
<img width="1035" alt="Screenshot 2023-05-12 at 11 09 03 pm" src="https://github.com/AdamXweb/WhiteSurFirefoxThemeMacOS/assets/6800453/021c6119-d106-4c4a-b5ed-3fa32658d233">
