### ISSUE TITLE
[BUG] Firefox v113 tabsbar alignment bug

### ISSUE THREAD

**Issue by vcoss-adam** [AdamXweb/WhiteSurFirefoxThemeMacOS#86]
### Describe the problem

Tabsbar no longer displays under URLbar.

![image](https://github.com/AdamXweb/WhiteSurFirefoxThemeMacOS/assets/132973209/276d4b8c-8225-42f9-99a2-ea83187d9f25)

See https://github.com/vinceliuice/WhiteSur-firefox-theme/issues/23 for more info

### Version

1.5.1

### OS

Windows 11

### Firefox Version

113

### Install Options

none

### Colour Theme

n/a

### Please tick the boxes

- [X] You are using a [current](https://github.com/AdamXweb/WhiteSurFirefoxThemeMacOS/releases/) version of the theme. (check the date associated with the version)
- [X] You've checked that this [issue hasn't already been raised](https://github.com/adamxweb/WhiteSurFirefoxThemeMacOS/issues?q=is%3Aissue)

**Comment by AdamXweb** [comment]
Have tested on MacOS and Windows, confirmed working on v113
<img width="1188" alt="Screenshot 2023-05-12 at 10 46 15 pm" src="https://github.com/AdamXweb/WhiteSurFirefoxThemeMacOS/assets/6800453/59d8d3be-5849-4c67-93b6-9a6138ece657">

**Comment by AdamXweb** [comment]
https://github.com/AdamXweb/WhiteSurFirefoxThemeMacOS/releases/tag/v1.5.2 released with support for v113
