### ISSUE TITLE
the reserach bar change

### ISSUE THREAD

**Issue by gamerabbit16** [AdamXweb/WhiteSurFirefoxThemeMacOS#90]
### Is your feature request related to a problem? If so, please describe.

can we have like on the lattest mac os version, if you have one tab open dont have this ugly bar 
![image](https://github.com/AdamXweb/WhiteSurFirefoxThemeMacOS/assets/75642613/b1757fcf-0ea2-4d5d-b673-6931905a84ef)
thanks

### Describe the solution you'd like

have no bar, some thing like this 
![image](https://github.com/AdamXweb/WhiteSurFirefoxThemeMacOS/assets/75642613/4b117ddd-aa45-4e10-9f3a-782205d5cc9b)

### Priority

Low (Nice-to-have)

### Is this something you would be keen to implement

No

**Comment by AdamXweb** [comment]
Hi @gamerabbit16, you can install with the option `-s` or copying the `https://github.com/AdamXweb/WhiteSurFirefoxThemeMacOS/blob/master/custom/singletabhidden.css`.
