### ISSUE TITLE
Traffic lights got inverted after 113.1 update

### ISSUE THREAD

**Issue by F3R96** [AdamXweb/WhiteSurFirefoxThemeMacOS#91]
### Describe the problem

![imagen](https://github.com/AdamXweb/WhiteSurFirefoxThemeMacOS/assets/78397863/70dcd6e7-208d-4015-9726-8ed93cb13bc6)
They used to look like this 
![imagen](https://github.com/AdamXweb/WhiteSurFirefoxThemeMacOS/assets/78397863/a999bfa5-3cea-48af-9689-0a6db2df19ed)
Any chance of a fix ? 

### Version

1.5.2

### OS

Windows 10

### Firefox Version

113.1

### Install Options

none

### Colour Theme

No

### Please tick the boxes

- [X] You are using a [current](https://github.com/AdamXweb/WhiteSurFirefoxThemeMacOS/releases/) version of the theme. (check the date associated with the version)
- [X] You've checked that this [issue hasn't already been raised](https://github.com/adamxweb/WhiteSurFirefoxThemeMacOS/issues?q=is%3Aissue)

**Comment by AjaykrishnanR-axon** [comment]
same issue, wondering if i was the only one

**Comment by GameBoyzGB** [comment]
Been waiting for a fix for a few days now. It is so inconvenient to click what is supposed to be the close button only to minimize it. Please fix this. Thank you!

**Comment by AdamXweb** [comment]
Hi @GameBoyzGB , i understand your frustration and appreciate your usage of my theme. This is an open source project that I work on in my spare time and I don't always have access to a Windows machine. The problem occurred with the update changing the elements the browser used to 'flex' which is more web driven. If you'd like to help test a fix, yhe problem will be in this file below on Line 41, can you please try changing the order value to -1

https://github.com/AdamXweb/WhiteSurFirefoxThemeMacOS/blob/master/chrome/WhiteSur/parts/windows.css

Thanks

**Comment by AdamXweb** [comment]
And to those using the swapclose, line 21 needs to be tested also

https://github.com/AdamXweb/WhiteSurFirefoxThemeMacOS/blob/master/custom/windows-swapclose.css

To test, you can edit the file in that path on your machine and restart Firefox

**Comment by AjaykrishnanR-axon** [comment]
@AdamXweb yep it works ! thanks
