### ISSUE TITLE
problem in closing minimizing and maximizing button[BUG]

### ISSUE THREAD

**Issue by ayaan07alam** [AdamXweb/WhiteSurFirefoxThemeMacOS#94]
![image](https://github.com/AdamXweb/WhiteSurFirefoxThemeMacOS/assets/77435615/aa6f44c7-a41f-4875-82d5-5345618d52f4)
how to solve this issue???

**Comment by AdamXweb** [comment]
Hi @ayaan07alam, if you'd like assistance fixing this issue, please fill out the bug report with the info below


Describe the problem

Version

OS

Firefox Version

Install Options

Colour Theme

Additional info

**Comment by AdamXweb** [comment]
Closing as no additional information was provided. Unable to reproduce the issue
