### ISSUE TITLE
[BUG] Tab Close wrong position

### ISSUE THREAD

**Issue by 1-800-aesthetics** [AdamXweb/WhiteSurFirefoxThemeMacOS#99]
### Describe the problem

The close tabs button is in the wrong position

Since the bug started "[BUG] Close, Minimize, Maximize button bugged out! #98" @MatsCraft1 (thanks)
and today that @easonwong-de fixed (thanks ) i see that but i didn't have the courage to report because my memory is bad and I could be wrong.

> - So if i'm wrong i apologize

### Version

v1.5.2 2023-05-12 Latest

### OS

Windows 11

### Firefox Version

117.0

### Install Options

none

### Colour Theme

none

### Additional info

![image](https://github.com/AdamXweb/WhiteSurFirefoxThemeMacOS/assets/102426598/b9b26045-e48f-4612-9f5a-553a9995aaad)

### Please tick the boxes

- [X] You are using a [current](https://github.com/AdamXweb/WhiteSurFirefoxThemeMacOS/releases/) version of the theme. (check the date associated with the version)
- [X] You've checked that this [issue hasn't already been raised](https://github.com/adamxweb/WhiteSurFirefoxThemeMacOS/issues?q=is%3Aissue)

**Comment by AdamXweb** [comment]
Thanks for submitting this issue. I'm trying to replicate this, could you please advise the URL of the webpage, or if it has any media, is a system page etc.

**Comment by 1-800-aesthetics** [comment]
Well this is happening when opening a new tab, in any URL, after thinking I found a better way to explain:
the close button, for tabs, is using firefox's default and not the theme's, thus becoming the same as the photo above

**Comment by AdamXweb** [comment]
<img width="876" alt="Screenshot 2023-09-05 at 3 46 42 pm" src="https://github.com/AdamXweb/WhiteSurFirefoxThemeMacOS/assets/6800453/8c5f9deb-836d-4843-aae0-084c74e659e8">

I can't seem to reproduce the issue. Could you try the latest release and advise if that fixes the issue?

**Comment by 1-800-aesthetics** [comment]
I installed adding customs was having the same problem. So I decided to delete everything and install clean, thank you very much
everything is working perfectly (with nothing installed in .../custom), later I will select each item to put it again, if I find out what caused this error, I will inform you here
